/**
 * jQuery Cookie plugin
 *
 * Copyright (c) 2010 Klaus Hartl (stilbuero.de)
 * Dual licensed under the MIT and GPL licenses:
 * http://www.opensource.org/licenses/mit-license.php
 * http://www.gnu.org/licenses/gpl.html
 *
 */
jQuery.cookie=function(a,b,c){var d,e,f,g;return arguments.length>1&&"[object Object]"!==String(b)?(c=jQuery.extend({},c),(null===b||void 0===b)&&(c.expires=-1),"number"==typeof c.expires&&(d=c.expires,e=c.expires=new Date,e.setDate(e.getDate()+d)),b=String(b),document.cookie=[encodeURIComponent(a),"=",c.raw?b:encodeURIComponent(b),c.expires?"; expires="+c.expires.toUTCString():"",c.path?"; path="+c.path:"",c.domain?"; domain="+c.domain:"",c.secure?"; secure":""].join("")):(c=b||{},g=c.raw?function(a){return a}:decodeURIComponent,(f=new RegExp("(?:^|; )"+encodeURIComponent(a)+"=([^;]*)").exec(document.cookie))?g(f[1]):null)},function(a){function c(a){return"object"==typeof a?a:{top:a,left:a}}var b=a.scrollTo=function(b,c,d){a(window).scrollTo(b,c,d)};b.defaults={axis:"xy",duration:parseFloat(a.fn.jquery)>=1.3?0:1,limit:!0},b.window=function(){return a(window)._scrollable()},a.fn._scrollable=function(){return this.map(function(){var d,b=this,c=!b.nodeName||-1!=a.inArray(b.nodeName.toLowerCase(),["iframe","#document","html","body"]);return c?(d=(b.contentWindow||b).document||b.ownerDocument||b,/webkit/i.test(navigator.userAgent)||"BackCompat"==d.compatMode?d.body:d.documentElement):b})},a.fn.scrollTo=function(d,e,f){return"object"==typeof e&&(f=e,e=0),"function"==typeof f&&(f={onAfter:f}),"max"==d&&(d=9e9),f=a.extend({},b.defaults,f),e=e||f.duration,f.queue=f.queue&&f.axis.length>1,f.queue&&(e/=2),f.offset=c(f.offset),f.over=c(f.over),this._scrollable().each(function(){function m(a){h.animate(k,e,f.easing,a&&function(){a.call(this,d,f)})}if(null!=d){var j,g=this,h=a(g),i=d,k={},l=h.is("html,body");switch(typeof i){case"number":case"string":if(/^([+-]=)?\d+(\.\d+)?(px|%)?$/.test(i)){i=c(i);break}if(i=a(i,this),!i.length)return;case"object":(i.is||i.style)&&(j=(i=a(i)).offset())}a.each(f.axis.split(""),function(a,c){var q,d="x"==c?"Left":"Top",e=d.toLowerCase(),n="scroll"+d,o=g[n],p=b.max(g,c);j?(k[n]=j[e]+(l?0:o-h.offset()[e]),f.margin&&(k[n]-=parseInt(i.css("margin"+d))||0,k[n]-=parseInt(i.css("border"+d+"Width"))||0),k[n]+=f.offset[e]||0,f.over[e]&&(k[n]+=i["x"==c?"width":"height"]()*f.over[e])):(q=i[e],k[n]=q.slice&&"%"==q.slice(-1)?parseFloat(q)/100*p:q),f.limit&&/^\d+$/.test(k[n])&&(k[n]=k[n]<=0?0:Math.min(k[n],p)),!a&&f.queue&&(o!=k[n]&&m(f.onAfterFirst),delete k[n])}),m(f.onAfter)}}).end()},b.max=function(b,c){var f,g,h,d="x"==c?"Width":"Height",e="scroll"+d;return a(b).is("html,body")?(f="client"+d,g=b.ownerDocument.documentElement,h=b.ownerDocument.body,Math.max(g[e],h[e])-Math.min(g[f],h[f])):b[e]-a(b)[d.toLowerCase()]()}}(jQuery);