<?php
if (!defined('__TYPECHO_ROOT_DIR__')) exit;

class Sitemap_Action extends Typecho_Widget implements Widget_Interface_Do
{
	const DEFAULT_FILE_NAME = 'sitemap.xml';
	const STATIC_MARKER = '<!-- Generated by Typecho Sitemap plugin -->';

	private static $instance = 0;

	public function action()
	{
		header("Content-Type: application/xml");
		echo $this->generateXml();
	}

	public static function generateStatic($minTagCount = NULL, $fileName = self::DEFAULT_FILE_NAME)
	{
		$fileName = self::normalizeFileName($fileName);
		if (false === $fileName) {
			return false;
		}

		$generator = Typecho_Widget::widget(
			'Sitemap_Action@sitemapStatic' . (++self::$instance)
		);
		$xml = self::addStaticMarker($generator->generateXml($minTagCount));

		return self::writeStaticFile($xml, $fileName);
	}

	public static function removeStaticFile($fileName = self::DEFAULT_FILE_NAME)
	{
		$fileName = self::normalizeFileName($fileName);
		if (false === $fileName) {
			return false;
		}

		$path = self::staticFilePath($fileName);
		if (!file_exists($path) || !self::isManagedStaticFile($path)) {
			return true;
		}

		return @unlink($path);
	}

	public static function normalizeFileName($fileName)
	{
		$fileName = trim((string) $fileName);
		if (
			strlen($fileName) > 128
			|| !preg_match('/\\A[A-Za-z0-9][A-Za-z0-9_-]*\\.xml\\z/', $fileName)
		) {
			return false;
		}

		return $fileName;
	}

	public static function canUseFileName($fileName)
	{
		$fileName = self::normalizeFileName($fileName);
		if (false === $fileName) {
			return false;
		}

		$path = self::staticFilePath($fileName);
		return !file_exists($path) || self::isManagedStaticFile($path);
	}

	private function generateXml($minTagCount = NULL)
	{
		$db = Typecho_Db::get();
		$options = Typecho_Widget::widget('Widget_Options');
		$instance = ++self::$instance;

		$pages = $db->fetchAll($db->select()->from('table.contents')
			->where('table.contents.status = ?', 'publish')
			->where('table.contents.created < ?', $options->gmtTime)
			->where('table.contents.type = ?', 'page')
			->order('table.contents.created', Typecho_Db::SORT_DESC));

		$articleCount = $db->fetchObject($db->select(array('COUNT(table.contents.cid)' => 'num'))
			->from('table.contents')
			->where('table.contents.status = ?', 'publish')
			->where('table.contents.created < ?', $options->time)
			->where('table.contents.type = ?', 'post'))->num;

		Typecho_Widget::widget(
			'Widget_Contents_Post_Recent@sitemapArticles' . $instance,
			'pageSize=' . max(1, (int) $articleCount)
		)->to($articles);

		Typecho_Widget::widget('Widget_Metas_Category_List@cate' . $instance)->to($cates);

		$tags = $db->fetchAll($db->select()->from('table.metas')
			->where('table.metas.type = ?', 'tag')
			->order('table.metas.mid', Typecho_Db::SORT_DESC));

		if (NULL === $minTagCount) {
			$minTagCount = max(1, (int) $options->plugin('Sitemap')->minTagCount);
		} else {
			$minTagCount = max(1, (int) $minTagCount);
		}

		$xml = "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n";
		$xml .= "<?xml-stylesheet type='text/xsl' href='" . $options->pluginUrl . "/Sitemap/sitemap.xsl'?>\n";
		$xml .= "<urlset xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n";
		$xml .= "xsi:schemaLocation=\"http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd\"\n";
		$xml .= "xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\">";
		$xml .= "\t<url>\n";
		$xml .= "\t\t<loc>" . $options->siteUrl . "</loc>\n";
		$xml .= "\t\t<changefreq>daily</changefreq>\n";
		$xml .= "\t\t<priority>1.0</priority>\n";
		$xml .= "\t</url>\n";

		foreach ($pages as $page) {
			$type = $page['type'];
			$routeExists = (NULL != Typecho_Router::get($type));
			$page['pathinfo'] = $routeExists ? Typecho_Router::url($type, $page) : '#';
			$page['permalink'] = Typecho_Common::url($page['pathinfo'], $options->index);

			$xml .= "\t<url>\n";
			$xml .= "\t\t<loc>" . $page['permalink'] . "</loc>\n";
			$xml .= "\t\t<lastmod>" . date('Y-m-d', $page['modified']) . "</lastmod>\n";
			$xml .= "\t\t<changefreq>always</changefreq>\n";
			$xml .= "\t\t<priority>0.6</priority>\n";
			$xml .= "\t</url>\n";
		}

		while ($articles->next()) {
			$xml .= "\t<url>\n";
			$xml .= "\t\t<loc>" . $articles->permalink . "</loc>\n";
			$xml .= "\t\t<lastmod>" . date('Y-m-d', $articles->modified) . "</lastmod>\n";
			$xml .= "\t\t<changefreq>always</changefreq>\n";
			$xml .= "\t\t<priority>0.8</priority>\n";
			$xml .= "\t</url>\n";
		}

		while ($cates->next()) {
			$artRs = $db->fetchRow($db->select()->from('table.contents')
				->join('table.relationships', 'table.contents.cid = table.relationships.cid')
				->where('table.contents.status = ?', 'publish')
				->where('table.relationships.mid = ?', $cates->mid)
				->order('table.relationships.cid', Typecho_Db::SORT_DESC)
				->limit(1));

			if (empty($artRs['modified'])) {
				continue;
			}

			$xml .= "\t<url>\n";
			$xml .= "\t\t<loc>" . $cates->permalink . "</loc>\n";
			$xml .= "\t\t<lastmod>" . date('Y-m-d', $artRs['modified']) . "</lastmod>\n";
			$xml .= "\t\t<changefreq>daily</changefreq>\n";
			$xml .= "\t\t<priority>0.5</priority>\n";
			$xml .= "\t</url>\n";
		}

		foreach ($tags as $tag) {
			$type = $tag['type'];
			$tagArticles = $db->fetchAll($db->select('table.contents.modified')->from('table.contents')
				->join('table.relationships', 'table.contents.cid = table.relationships.cid')
				->where('table.contents.status = ?', 'publish')
				->where('table.contents.created < ?', $options->time)
				->where('table.contents.type = ?', 'post')
				->where('table.relationships.mid = ?', $tag['mid'])
				->order('table.contents.modified', Typecho_Db::SORT_DESC)
				->limit($minTagCount));

			if (count($tagArticles) < $minTagCount) {
				continue;
			}
			$latestTagArticle = current($tagArticles);

			$routeExists = (NULL != Typecho_Router::get($type));
			$tag['pathinfo'] = $routeExists ? Typecho_Router::url($type, $tag) : '#';
			$tag['permalink'] = Typecho_Common::url($tag['pathinfo'], $options->index);

			$xml .= "\t<url>\n";
			$xml .= "\t\t<loc>" . $tag['permalink'] . "</loc>\n";
			$xml .= "\t\t<lastmod>" . date('Y-m-d', $latestTagArticle['modified']) . "</lastmod>\n";
			$xml .= "\t\t<changefreq>daily</changefreq>\n";
			$xml .= "\t\t<priority>0.5</priority>\n";
			$xml .= "\t</url>\n";
		}

		$xml .= "</urlset>";
		return $xml;
	}

	private static function addStaticMarker($xml)
	{
		$lineEnd = strpos($xml, "\n");
		if (false === $lineEnd) {
			return self::STATIC_MARKER . "\n" . $xml;
		}

		return substr($xml, 0, $lineEnd + 1)
			. self::STATIC_MARKER . "\n"
			. substr($xml, $lineEnd + 1);
	}

	private static function writeStaticFile($xml, $fileName)
	{
		$fileName = self::normalizeFileName($fileName);
		if (false === $fileName) {
			return false;
		}

		$path = self::staticFilePath($fileName);
		$directory = dirname($path);

		if (file_exists($path) && !self::isManagedStaticFile($path)) {
			return false;
		}
		if (!is_writable($directory)) {
			return false;
		}
		if (is_file($path) && @file_get_contents($path) === $xml) {
			return true;
		}

		$temporaryPath = tempnam($directory, '.sitemap-');
		if (false === $temporaryPath) {
			return false;
		}

		$written = file_put_contents($temporaryPath, $xml, LOCK_EX);
		if (strlen($xml) !== $written) {
			@unlink($temporaryPath);
			return false;
		}

		@chmod($temporaryPath, 0644);
		if (!@rename($temporaryPath, $path)) {
			@unlink($temporaryPath);
			return false;
		}

		clearstatcache(true, $path);
		return true;
	}

	private static function staticFilePath($fileName)
	{
		return rtrim(__TYPECHO_ROOT_DIR__, DIRECTORY_SEPARATOR)
			. DIRECTORY_SEPARATOR . $fileName;
	}

	private static function isManagedStaticFile($path)
	{
		$handle = @fopen($path, 'rb');
		if (false === $handle) {
			return false;
		}

		$prefix = fread($handle, 512);
		fclose($handle);

		return is_string($prefix) && false !== strpos($prefix, self::STATIC_MARKER);
	}
}
